server:
  port: ${PORT:9111}
spring:
  application:
    name: proxy-service
eureka:
  instance:
    hostname: ${EUREKA_HOSTNAME:localhost:${eureka.port}}
  port: 9110
  user: ${EUREKA_USER_NAME:user}
  password: ${EUREKA_USER_PASSWORD:password}
  client:
    preferIpAddress: true
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://${eureka.user}:${eureka.password}@${eureka.instance.hostname}/eureka/
